version: "3"
services:
  mosquitto:
    image: mosquitto:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - mosquittonet
networks:
  mosquittonet:
